### ISSUE TITLE
process reference information

### ISSUE THREAD

**Issue by Pz1c** [Pz1c/WavingHands#137]
process ref params after install #77

https://stackoverflow.com/questions/25466443/how-to-use-app-links-to-pass-parameter-to-android-playstore-to-be-retrieved-when

**Comment by Pz1c** [comment]
dependent on #105

**Comment by Pz1c** [comment]
thanks @SimonMarquis for example

**Comment by Pz1c** [comment]
```
System.err: java.lang.NoSuchMethodError: no static method "Lorg/qtproject/example/androidnotifier/NotificationClient;.get_refferer()Ljava/lang/String;"
W System.err: 	at org.qtproject.qt.android.QtNative.startQtApplication(Native Method)
W System.err: 	at org.qtproject.qt.android.QtNative$7.run(QtNative.java:633)
W System.err: 	at org.qtproject.qt.android.QtThread$1.run(QtThread.java:61)
W System.err: 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by Pz1c** [comment]
problem fixed, ready to live
